"""Контракт human-edited inputs и generated dependency locks."""

from __future__ import annotations

import tomllib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "requirements.txt"
DEV_REQUIREMENTS = ROOT / "requirements-dev.txt"
REQUIREMENTS_INPUT = ROOT / "requirements.in"
DEV_REQUIREMENTS_INPUT = ROOT / "requirements-dev.in"
PYPROJECT = ROOT / "pyproject.toml"
INSTALLER = ROOT / "scripts" / "install.sh"
CI_CHECKS = ROOT / ".github" / "workflows" / "_checks.yml"
DOCKERFILE = ROOT / "Dockerfile"

RUNTIME_PINS = {
    "caldav==3.2.1",
    "cryptography==49.0.0",
    "icalendar==7.2.2",
    "python-dotenv==1.2.2",
    "requests==2.34.2",
    "Pillow==12.3.0",
}
DEV_PINS = {
    "pytest==9.1.1",
    "ruff==0.16.0",
    "mypy==2.3.0",
    "pre-commit==4.6.1",
    "uv==0.11.32",
}


def _active_lines(path: Path) -> set[str]:
    return {
        line
        for raw_line in path.read_text(encoding="utf-8").splitlines()
        if (line := raw_line.strip()) and not line.startswith("#")
    }


@pytest.mark.parametrize("pin", sorted(RUNTIME_PINS))
def test_runtime_input_dependency_is_exactly_pinned(pin: str) -> None:
    assert pin in _active_lines(REQUIREMENTS_INPUT)


@pytest.mark.parametrize("pin", sorted(DEV_PINS))
def test_dev_input_dependency_is_exactly_pinned(pin: str) -> None:
    assert pin in _active_lines(DEV_REQUIREMENTS_INPUT)


def test_dependency_inputs_contain_only_direct_pins() -> None:
    assert _active_lines(REQUIREMENTS_INPUT) == RUNTIME_PINS
    assert _active_lines(DEV_REQUIREMENTS_INPUT) == {"-r requirements.in", *DEV_PINS}


def _locked_requirement_lines(path: Path) -> list[str]:
    return [
        line
        for raw_line in path.read_text(encoding="utf-8").splitlines()
        if (line := raw_line.strip()) and not line.startswith(("#", "-", ";")) and line[0].isalnum()
    ]


@pytest.mark.parametrize("path", [REQUIREMENTS, DEV_REQUIREMENTS])
def test_generated_lock_contains_only_exact_versions(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    assert "This file was autogenerated by uv" in text
    requirement_lines = _locked_requirement_lines(path)
    assert requirement_lines
    assert all("==" in line.split(";", 1)[0] for line in requirement_lines)


@pytest.mark.parametrize("pin", sorted(RUNTIME_PINS))
def test_runtime_direct_pin_is_present_in_both_locks(pin: str) -> None:
    normalized = pin.lower()
    assert any(
        line.lower().startswith(normalized) for line in _locked_requirement_lines(REQUIREMENTS)
    )
    assert any(
        line.lower().startswith(normalized) for line in _locked_requirement_lines(DEV_REQUIREMENTS)
    )


@pytest.mark.parametrize("pin", sorted(DEV_PINS))
def test_dev_direct_pin_is_present_in_dev_lock(pin: str) -> None:
    normalized = pin.lower()
    assert any(
        line.lower().startswith(normalized) for line in _locked_requirement_lines(DEV_REQUIREMENTS)
    )


def test_requests_does_not_use_external_stubs() -> None:
    assert all(
        not line.lower().startswith("types-requests") for line in _active_lines(DEV_REQUIREMENTS)
    )


def test_python_baseline_is_consistent() -> None:
    pyproject = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    assert pyproject["project"]["requires-python"] == ">=3.11"
    assert pyproject["tool"]["ruff"]["target-version"] == "py311"
    assert pyproject["tool"]["mypy"]["python_version"] == "3.11"
    assert "sys.version_info >= (3, 11)" in INSTALLER.read_text(encoding="utf-8")
    assert 'python-version: ["3.11", "3.12"]' in CI_CHECKS.read_text(encoding="utf-8")
    assert DOCKERFILE.read_text(encoding="utf-8").startswith("FROM python:3.12-")
