http:
  routers:
    http-to-https:
      rule: Host(`cassinilab.ru`)
      entryPoints:
        - web
      middlewares:
        - redirect-https
      service: noop@internal
      priority: 1

  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
