"""Neutral Rich HTML formatting facade for draft/status text."""

from __future__ import annotations

from ..telegram_bot.rich_message import (
    RICH_MESSAGE_CHAR_LIMIT,
    RICH_MESSAGE_SAFETY_CAP,
    anchor,
    anchor_link,
    blockquote,
    bold,
    code,
    datetime_link,
    details_block,
    divider,
    escape_rich,
    footnote_def,
    footnote_ref,
    input_rich_message,
    italic,
    join_blocks,
    mark,
    ordered_list,
    paragraph,
    pull_quote,
    reference,
    rich_blocks_for_streaming,
    section_heading,
    spoiler,
    strikethrough,
    subscript,
    superscript,
    table,
    thinking_block,
    truncate_rich_html,
    underline,
    unordered_list,
)

__all__ = [
    "RICH_MESSAGE_CHAR_LIMIT",
    "RICH_MESSAGE_SAFETY_CAP",
    "anchor",
    "anchor_link",
    "blockquote",
    "bold",
    "code",
    "datetime_link",
    "details_block",
    "divider",
    "escape_rich",
    "footnote_def",
    "footnote_ref",
    "input_rich_message",
    "italic",
    "join_blocks",
    "mark",
    "ordered_list",
    "paragraph",
    "pull_quote",
    "reference",
    "rich_blocks_for_streaming",
    "section_heading",
    "spoiler",
    "strikethrough",
    "subscript",
    "superscript",
    "table",
    "thinking_block",
    "truncate_rich_html",
    "underline",
    "unordered_list",
]
